---
# tools-specific configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: jobs-emailer-configmap
  namespace: jobs-emailer
data:
  "task_compose_emails_loop_sleep": "150"
  "task_send_emails_loop_sleep": "10"
  "task_send_emails_max": "10"
  "task_watch_pods_timeout": "60"
  "task_read_configmap_sleep": "10"
  "email_to_domain": "tools.wmflabs.org"
  "email_to_prefix": "tools"
  "email_from_addr": "root@toolforge.org"
  "smtp_server_fqdn": "mail.tools.wmflabs.org"
  "smtp_server_port": "25"
  "send_emails_for_real": "yes"
  "debug": "no"
