---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-emailer
  namespace: jobs-emailer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jobs-emailer
    spec:
      serviceAccountName: jobs-emailer
      containers:
        - name: jobs-emailer
          image: docker-registry.tools.wmflabs.org/toolforge-jobs-framework-emailer:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 999
          ports:
            - name: webserver
              containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            # 28 seconds is periodSeconds (30) minus 2, meaning: timeout just before the next probe
            timeoutSeconds: 28
            httpGet:
              path: /healthz
              port: webserver
