---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jobs-emailer-configmap
  namespace: jobs-emailer
data:
  "task_compose_emails_loop_sleep": "30"
  "task_send_emails_loop_sleep": "10"
  "task_send_emails_max": "2"
  "task_watch_pods_timeout": "60"
  "task_read_configmap_sleep": "10"
  "email_to_domain": "toolsbeta.wmflabs.org"
  "email_to_prefix": "toolsbeta"
  "email_from_addr": "root@toolforge.org"
  "smtp_server_fqdn": "mail.toolforge.org"
  "smtp_server_port": "465"
  "send_emails_for_real": "no"
  "debug": "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-emailer
  namespace: jobs-emailer
  labels:
    name: jobs-emailer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jobs-emailer
  template:
    metadata:
      labels:
        name: jobs-emailer
    spec:
      serviceAccountName: jobs-emailer
      containers:
        - name: emailer
          image: jobs-emailer:latest
          imagePullPolicy: Never
---
